// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.itmuch.proto;

public interface StreamRequsetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.itmuch.proto.StreamRequset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestinfo = 1;</code>
   */
  java.lang.String getRequestinfo();
  /**
   * <code>string requestinfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestinfoBytes();
}
