// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.itmuch.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.itmuch.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseinfo = 1;</code>
   */
  java.lang.String getResponseinfo();
  /**
   * <code>string responseinfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseinfoBytes();
}
