// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.itmuch.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.itmuch.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.itmuch.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.itmuch.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.itmuch.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.itmuch.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.itmuch.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.itmuch.proto.StudentResponse studentResponse = 1;</code>
   */
  com.itmuch.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
